[BCTC-253] - need new type for homework submission
BCTCio/typed pull request #5
Opened 2021-10-24 00:35 UTC by leocabbage2008

2021-10-24 16:09 UTC, chuxu200328 requested changes

2021-10-24 16:09 UTC, chuxu200328 commented on fs/index.ts
> +export interface IHomework {
ISubmission is better

2021-10-24 16:09 UTC, chuxu200328 commented on fs/index.ts
> +  comment:string;
what is comment?

2021-10-24 18:01 UTC, leocabbage2008 commented on fs/index.ts
> +  comment:string;
this, 
![image](https://user-images.githubusercontent.com/70451398/138604179-883c8374-50cf-4ba1-b503-9963011decc4.png)

2021-10-24 18:22 UTC, chuxu200328 commented on fs/index.ts
> +  comment:string;
that should be the original content. the new filed should be link.

2021-10-26 00:52 UTC, chuxu200328 approved these changes

2021-10-26 00:53 UTC, merged